engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript

ratings:
   paths:
   - "**.rb"

exclude_paths:
- spec/**/*
- db/**/*
- bin/**/*